### ISSUE TITLE
Implement option to ignore MAC mismatch similar to `sops --ignore-mac`

### ISSUE THREAD

**Issue by nobbs** [nobbs/terraform-provider-sops#23]
Follow up of #9.

The terraform file

```hcl
terraform {
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
      version = "1.19.0"
    }

    sops = {
      source = "nobbs/sops"
      version = "0.2.1"
    }
  }
}

data "kubectl_path_documents" "docs_sops" {
  pattern = "files/b.sops.yaml"
  disable_template = true
}

output "docs_sops" {
  value = [
    for k, v in data.kubectl_path_documents.docs_sops.manifests : provider::sops::string(v, "yaml")
  ]
}
```

with the encrypted file 

```yaml
apiVersion: ENC[AES256_GCM,data:YBA=,iv:ePq8JDb9L7z+ysEJu5BuCLS1rPfieMedGuUsfrrbbWo=,tag:s7L4VmBznCeyUrubcvC0Vg==,type:str]
kind: ENC[AES256_GCM,data:XaqS,iv:PEKrk/y86r12Y0elCsLipoTuIUbkqkD1ND9qieWnp1A=,tag:rkxtQ6WlCh6IAh6Mr9J8ig==,type:str]
metadata:
  name: ENC[AES256_GCM,data:ZN8TH56QjO6dmWE=,iv:LJLpDsiYZUqYK0P+wl4Zwa3KHz81FH9dSpEmq7nb/RM=,tag:pJKU0pte3gwEUhX/KFQ2/Q==,type:str]
spec:
  containers:
    - name: ENC[AES256_GCM,data:CnsvpDISXpzsA5teevCXekc=,iv:EWryacQcfDvTX0oDsTY9N+TiT5vDrd14ZifhzreLoWc=,tag:oSOnM+AAmaUXtYbzzorLfg==,type:str]
      image: ENC[AES256_GCM,data:uwA90ddlcWt8Mtxr,iv:/6GPKc9VJgMAkmUChkUXoLQ1pORVOBRrdOxI2glm9Q4=,tag:jB9hLGHmSziY/MjtdPPvew==,type:str]
      ports:
        - containerPort: ENC[AES256_GCM,data:5V8=,iv:6zYn3H2Kct1H/eCYa5uK/vaUqemiSkiP1NBDULEghQY=,tag:sbv9+lgBmzu4jIVL7NkWRA==,type:int]
sops:
  age:
    - recipient: age1cxgy6y5vctq5vy6dn4s3takyexa4n83cueuv8m0j0ngv2w6ff39qfguyjn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcjIwb29LNm0rOFJpN1RY
        SE5VVnNCR2JDM1FTaFlIZ3dzVVkzZkJjUWswCm93MG5VZElGODRabjFOcnpLTmt0
        OGFtTVltOTZCVVVEWVJuT0l4bTNKOG8KLS0tIFl2akMzcjloYm9mbUVFRWNnTW1N
        bDl4S3BiMmorUzNyVk12VmVyZjVIRFEKXDFWaHBybUAILTc5RVL/0gbqS94BY6Jy
        TPI+9EId42Bf3vr0VSVGFC6t2bvqOLgFfkDUN4Zs6ez25N2lmJYvkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-21T11:13:28Z"
  mac: ENC[AES256_GCM,data:is6EX39tPx1TEQGTznOqW7z8k2+nLxaVj6Ympjc3Z1XaMOds/YUyAKtlYn73dEWkYrdPxHCjEQGSQNfPqFATYYFzjeD4rHEws6Vv9qBZ9Zv8ZYQY2JauX+iL84kZ/GHuKKycOtnv1IqSRLNTrhFSIbRCGjpEleozIzSYJAzvcZQ=,iv:pICPtfI5sxsnFBWsyXSuOkuhFnXjLxPTVPRyrHwWV+k=,tag:ao7H+zbNApwJmC5kz5RaRg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
```

results in the error

```console
$ terraform plan
data.kubectl_path_documents.docs_sops: Reading...
data.kubectl_path_documents.docs_sops: Read complete after 0s [id=f63ab9605aa78e0ed5b546d5c85bd9cbb76c97a3c58d291b7ef67713d58cb51e]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Error in function call
│ 
│   on main.tf line 22, in output "docs_sops":
│   22:     for k, v in data.kubectl_path_documents.docs_sops.manifests : provider::sops::string(v, "yaml")
│ 
│ Call to function "provider::sops::string" failed: failed to decrypt file: Failed to verify data integrity. expected mac "56D3C8EB7B575F865CE1382E64A78B184DFB0FD5DFBE49B5D90824FACA54EBC821AEB69024E4BD5CE640BD17DF06A3ACD83B50242B7F6A6D26E26626F50684E4", got
│ "DF4CAA0F3D5E2F817A62008A4641C33BBA8D075EEC817E0AA681AA0B07B8B4CD2BC80025582B901CF43920A9F77CAF1DD19134C15C65A408BCE0977D7C232CA9".
╵
```
